### ISSUE TITLE
app will not launch a

### ISSUE THREAD

**Issue by cubiclestorm** [Bitslo/CableGuardian#1]
App will not launch anymore. I see a red icon for it come up in my taskbar then close in a second

**Comment by cubiclestorm** [comment]
Turns out if the audio playback device is disconnected the app will crash on launch. The config file must be deleted

**Comment by Bitslo** [comment]
Hey, good catch, thank you! Sorry I didn't see your message earlier (haven't gotten an email notification from GitHub either, I think). I'm not an experienced GitHub user so I didn't really realize to check for issue reports here. Accidentally noticed it when publishing version 1.2.0 just now.

Anyway, I fixed this issue in version 1.2.1.
